version: '3.9'

services:

  backend:
    restart: unless-stopped
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: dev
    ports:
      - "4000:4000"
    networks:
      - transcendence
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    #ports:
    #  - 5434:5432
    expose:
       - "5432"
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: random
      POSTGRES_DB: pongOffice
    networks:
      - transcendence
    volumes:
      - dbvolume:/var/lib/postgresql/data

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - transcendence
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src

networks:
  transcendence:
    driver: bridge

volumes:
  dbvolume:
