version: '3.9'

services:

  backend:
    restart: unless-stopped
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: dev
    ports:
      - 4000:4000
    networks:
      - transcendence
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: arstneio42
      POSTGRES_USER: trans
      POSTGRES_DB: transcendence
      POSTGRES_HOST: postgres
    networks:
      - transcendence
    volumes:
      - dbvolume:/var/lib/postgresql/data

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - transcendence
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src

  dbadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    depends_on:
      - db
    networks:
      - transcendence

networks:
  transcendence:

volumes:
  dbvolume:
