version: '3.8'
services:
  dev-db:
    image: postgres:16
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: pjay
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - transcendance
networks:
  transcendance:
